version: '3'
services:
  telegrambot:
    image: jarvis-telegram-bot:v1.0.2
    environment:
      - MONGO_HOST=mongodb
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=admin2023
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=admin2023
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db