env: dev

log_level: DEBUG

super_admin: bunboque

jarvis:
  token: 6674956871:AAHVJ1cVVHrJKkpviVJyI9XK55TnAcUq5kQ
  user_name: jarvis1402_bot

mongodb:
  host: "localhost"
  database: telegram_bot
  username: user
  password: admin2023
  port: 27017
